### ISSUE TITLE
Conversion update for 1.5.2, 1.6 and 2.0

### ISSUE THREAD

**Issue by christian-rli** [OpenEnergyPlatform/omi#102]
Conversion between different versions of the metadata needs to be extended or rewritten. Versions 1.5.2, 1.6, 2.0 need support. Only forward support is necessary. Include tests and a short documentation on how to use the conversion function.

See #99

**Comment by Ludee** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Lody/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Lody/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">


n | # | Key v20 | Example
-- | -- | -- | --
1 | 1 | name | oep_oemetadata
2 | 2 | title | OEP OEMetadata
3 | 3 | id | https://databus.openenergyplatform.org/oeplatform/reference
4 | 5 | name | oep_oemetadata_table_example
5 | 6 | topics | model_draft, reference
6 | 7 | title | OEP OEMetadata Example Table
7 | 8 | path | http://openenergyplatform.org/dataedit/view/model_draft/oep_oemetadata_table_example
8 | 9 | description | Example table used to illustrate the OEMetadata structure and meaning.
9 | 10 | languages | en-GB, de-DE, fr-FR
10 | 11.1 | name | energy
11 | 11.2 | path | https://openenergy-platform.org/ontology/oeo/OEO_00000150
12 | 12 | keywords | example, ODbL-1.0, NFDI4Energy
13 | 13 | publicationDate | 15.10.2024
14 | 14.1 | start | 11.10.2024
15 | 14.2 | end | 01.01.2025
16 | 14.3 | isActive | True
17 | 15.1 | title | NFDI4Energy
18 | 15.2 | homepage | https://nfdi4energy.uol.de/
19 | 15.3 | documentation | https://nfdi4energy.uol.de/sites/about_us/
20 | 15.4 | sourceCode | https://github.com/NFDI4Energy
21 | 15.5 | contact | info@nfdi4energy.org
22 | 15.6 | grantNo | 501865131
23 | 15.7 | fundingAgency | Deutsche Forschungsgemeinschaft (DFG)
24 | 15.8 | fundingAgencyLogo | https://upload.wikimedia.org/wikipedia/commons/8/86/DFG-logo-blau.svg
25 | 15.9 | publisherLogo | https://reiner-lemoine-institut.de//wp-content/uploads/2015/09/rlilogo.png
26 | 16.1.1 | address | Rudower Chaussee 12, 12489 Berlin
27 | 16.1.2 | @id | https://www.wikidata.org/wiki/Q77077223
28 | 16.1.3 | longitude | 52.432822
29 | 16.1.4 | longitude | 13.5351004
30 | 16.2.1 | name | Berlin
31 | 16.2.2 | @id | https://www.wikidata.org/wiki/Q64
32 | 16.2.3 | resolutionValue | 100
33 | 16.2.4 | resolutionUnit | m
34 | 16.2.5 | boundingBox | [13.08825, 52.33859, 13.76104, 52.6754]
35 | 16.2.6 | crs | EPSG:4326
36 | 17.1 | referenceDate | 01.01.2020
37 | 17.2.1 | start | 2020-01-01T00:00:00+00:00
38 | 17.2.2 | end | 2020-01-01T23:59:30+00:00
39 | 17.2.3 | resolution | 30 s
40 | 17.2.4 | alignment | left
41 | 17.2.5 | aggregationType | current
42 | 18.1 | title | IPCC Sixth Assessment Report (AR6) - Climate Change 2023 - Synthesis   Report
43 | 18.2 | description | A Report of the Intergovernmental Panel on Climate Change
44 | 18.3 | path | https://www.ipcc.ch/report/ar6/syr/downloads/report/IPCC_AR6_SYR_FullVolume.pdf
45 | 18.4.1 | name | ODbL-1.0
46 | 18.4.2 | title | Open Data Commons Open Database License 1.0
47 | 18.4.3 | path | https://opendatacommons.org/licenses/odbl/1-0/index.html
48 | 18.4.4 | instruction | You are free to share and change, but you must attribute, and share   derivations under the same license. See   https://tldrlegal.com/license/odc-open-database-license-odbl for further   information.
49 | 18.4.5 | attribution | © Intergovernmental Panel on Climate Change 2023
50 | 18.4.6 | copyrightStatement | https://www.ipcc.ch/copyright/
51 | 19.1 | name | ODbL-1.0
52 | 19.2 | title | Open Data Commons Open Database License 1.0
53 | 19.3 | path | https://opendatacommons.org/licenses/odbl/1-0/index.html
54 | 19.4 | instruction | You are free to share and change, but you must attribute, and share   derivations under the same license. See   https://tldrlegal.com/license/odc-open-database-license-odbl for further   information.
55 | 19.5 | attribution | © Reiner Lemoine Institut
56 | 20.1 | title | Ludwig Hülk
57 | 20.2 | path | https://github.com/Ludee
58 | 20.2 | organization | Reiner Lemoine Institut
59 | 20.2 | roles | creator, dataCurator
60 | 20.3 | date | 21.10.2024
61 | 20.4 | object | data and metadata
62 | 20.5 | comment | Add general context.
63 | 21.1 | type | table
64 | 21.4 | format | PostgreSQL
65 | 21.5 | encoding | UTF-8
66 | 22.6.1.1 | name | year
67 | 22.6.1.2 | description | Reference year for which the data were collected.
68 | 22.6.1.3 | type | geometry(Point, 4326)
69 | 22.6.1.4 | nullable | True
70 | 22.6.1.5 | unit | MW
71 | 22.6.1.6.1 | name | wind energy converting unit
72 | 22.6.1.6.2 | path | https://openenergy-platform.org/ontology/oeo/OEO_00000044
73 | 22.6.1.7.1 | value | onshore
74 | 22.6.1.7.2 | name | onshore wind farm
75 | 22.6.1.7.3 | path | https://openenergy-platform.org/ontology/oeo/OEO_00000311
76 | 23.6.2 | primaryKey | id
77 | 23.6.3.1 | fields | id, version
78 | 23.6.3.2.1 | resource | model_draft.oep_oemetadata_table_example_version
79 | 23.6.3.2.2 | fields | id, version
80 | 23.7.1 | delimiter | ,
81 | 23.7.2 | decimalSeparator | .
82 | 24 | @id | https://databus.openenergyplatform.org/oeplatform/supply/wri_global_power_plant_database/2022-11-07
83 | 25 | @context | https://raw.githubusercontent.com/OpenEnergyPlatform/oemetadata/master/metadata/latest/context.json
84 | 26.1 | path | https://www.example.com
85 | 26.2 | badge | Platinum
86 | 27.1 | metadataVersion | OEMetadata-2.0
87 | 27.2.1 | name | CC0-1.0
88 | 27.2.2 | title | Creative Commons Zero v1.0 Universal
89 | 27.2.3 | path | https://creativecommons.org/publicdomain/zero/1.0/



</body>

</html>

**Comment by Ludee** [comment]
This is the mapping from v160 to v20
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Lody/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Lody/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">


n | # | Key v20 | # | Key v160 | comment
-- | -- | -- | -- | -- | --
1 | 1 | name |   |   | new!
2 | 2 | title |   |   | new!
3 | 3 | id |   |   | new!
4 | 5 | name | 1 | name | remove "schema."
5 | 6 | topics |   |   | new! (schema from name)
7 | 8 | path | 3 | id | rename key!
9 | 10 | languages | 5 | language | rename key!
14 | 14.1 | start |   |   | new!
15 | 14.2 | end |   |   | new!
16 | 14.3 | isActive |   |   | new!
17 | 15.1 | title |   |   | new!
26 | 16.1.1 | address | 10.1 | location | rename key
27 | 16.1.2 | @id |   |   | new!
28 | 16.1.3 | longitude |   |   | new!
29 | 16.1.4 | longitude |   |   | new!
30 | 16.2.1 | name | 10.2 | extent | rename key
31 | 16.2.2 | @id |   |   | new!
32 | 16.2.3 | resolutionValue | 10.3 | resolution | Split value and unit using the space
33 | 16.2.4 | resolutionUnit |   |   | new!
34 | 16.2.5 | boundingBox |   |   | new!
35 | 16.2.6 | crs |   |   | new!
50 | 18.4.6 | copyrightStatement |   |   | new!
57 | 20.2 | path | 14.2 | email | rename key
58 | 20.2 | organization |   |   | new!
59 | 20.2 | roles |   |   | new!
63 | 21.1 | type | 15.1 | profile | change 'profile' to 'type':'table'
  |   |   | 15.2 | name | remove duplicate table name
  |   |   | 15.3 | path | remove duplicate path
65 | 21.5 | encoding | 15.5 | encoding | different
69 | 22.6.1.4 | nullable |   |   | new!
  |   |   | 20.1 | metadata | remove!
  |   |   | 20.2 | dates | remove!
  |   |   | 20.3 | units | remove!
  |   |   | 20.4 | languages | remove!
  |   |   | 20.5 | licenses | remove!
  |   |   | 20.6 | review | remove!
  |   |   | 20.7 | null | remove!
  |   |   | 20.8 | todo | remove!



</body>

</html>

**Comment by Ludee** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Lody/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Lody/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">


new | 19
-- | --
rename key | 7
remove | 10
update | 1
  |  
  | 37



</body>

</html>

**Comment by Ludee** [comment]
There have been some additions to this mapping. I will not update here but create a proper documentation page.

**Comment by jh-RLI** [comment]
Sure, i will take a look at the changes over in oemetadata repo. Regarding the documentation: I was thinking about setting up mkdocs but for now didn't want to do it as time is pushing. If you want to go ahead and do it, I can provide instructions on how to use omi. For now, i will add this to the README.md .
