### ISSUE TITLE
OMI is detached from metadata repo

### ISSUE THREAD

**Issue by MGlauer** [OpenEnergyPlatform/omi#20]
OEP Metadata is now developed in its own repository. OMI should use the JSON-schema to parse the OEP metadata format.

**Comment by 4lm** [comment]
> OEP Metadata is now developed in its own repository.

https://github.com/OpenEnergyPlatform/metadata

> OMI should use the JSON-schema to parse the OEP metadata format.

Also `dataedit/metadata` in [oeplatform](https://github.com/OpenEnergyPlatform/oeplatform/tree/develop/dataedit/metadata) should make use the schemas and schema validation of `omi` and `metadata`. It also has some code logic which would be better suited to be part of `omi`. Tomorrow, I will look into this ... maybe this will also result in some synergies for the refactoring of `omi`.
