### ISSUE TITLE
Ordered lists in RDF

### ISSUE THREAD

**Issue by MGlauer** [OpenEnergyPlatform/omi#5]
JSON lists are inherently ordered. The RDF-based metadata use mostly properties which does not preserve orderings. We _could_ use RDFS list semantics, but those are (imo) mostly unneeded for the metadata as is.

Are (explicit) orderings necessary or can they be omitted?

**Comment by Ludee** [comment]
For the JSON-String we decided for an explicit ordering to improve readability.
I'm not sure if this is necessary for RDF as well.
If it is easy to implement I would always suggest ordered metadata strings.
