### ISSUE TITLE
Broken link in README.rst 

### ISSUE THREAD

**Issue by l-emele** [OpenEnergyPlatform/omi#7]
In file README.rst there is a link to https://metadata-tool.readthedocs.io/, however following the link you land on a page telling "SORRY  This page does not exist yet."

**Comment by MGlauer** [comment]
This package is not released yet. Hence, no documentation, yet

**Comment by MGlauer** [comment]
The packaging is currently WIP in [features/packaging](https://github.com/OpenEnergyPlatform/omi/tree/features/packaging)

This tool will be released under the acronym OMI (Open Metadata Integration)

**Comment by MGlauer** [comment]
omi is now released and the link works
