### ISSUE TITLE
decode-function fails in python3

### ISSUE THREAD

**Issue by christian-rli** [OpenEnergyPlatform/omi#9]
I ran into this error:

```
  File "/home/christianh/Schreibtisch/omi/env/lib/python3.7/site-packages/omi-0.0.2-py3.7.egg/omi/cli.py", line 42, in translate
    outfile.write(s.decode("utf-8"))
AttributeError: 'str' object has no attribute 'decode'
```

Stackoverflow [suggests](https://stackoverflow.com/questions/28583565/str-object-has-no-attribute-decode-python-3-error) to simply drop the `.decode("utf8")`, because with python3 all strings are unicode objects already. Removing it worked for me and the cli worked afterwards. Going to push it in a new branch and create a PR.

**Comment by MGlauer** [comment]
Closed in #10
